# Generated by Django 5.2.9 on 2026-07-24 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0009_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cafes/')),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
                ('price_for_two', models.PositiveIntegerField(default=0)),
                ('pure_veg', models.BooleanField(default=False)),
                ('serves_alcohol', models.BooleanField(default=False)),
                ('rooftop', models.BooleanField(default=False)),
                ('has_table_booking', models.BooleanField(default=True)),
                ('total_tables', models.PositiveIntegerField(default=5)),
                ('opening_time', models.TimeField(default='11:00')),
                ('closing_time', models.TimeField(default='23:00')),
                ('partner_name', models.CharField(blank=True, max_length=150)),
                ('partner_email', models.EmailField(blank=True, max_length=254)),
                ('partner_phone', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cafes',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CafePartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('price_for_two', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('pure_veg', models.BooleanField(default=False)),
                ('serves_alcohol', models.BooleanField(default=False)),
                ('rooftop', models.BooleanField(default=False)),
                ('has_table_booking', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resulting_cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='cafes.cafe')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cafe_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cafe_partner_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('party_size', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='login.match')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cafes.cafe')),
            ],
            options={
                'db_table': 'cafe_bookings',
                'ordering': ['-date', '-time_slot'],
                'indexes': [models.Index(fields=['cafe', 'date', 'time_slot'], name='cafe_bookin_cafe_id_98e58f_idx')],
            },
        ),
    ]
