# Generated by Django 5.2.9 on 2026-07-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_email_userprofile_one_profile_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completion_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.IntegerField(default=0),
        ),
    ]
